### ISSUE TITLE
Move everything not needed for 'tracker-core' into the 'java-tracker'

### ISSUE THREAD

**Issue by jonalmeida** [snowplow/snowplow-java-tracker#81]
Looking back at what we have currently, we have a better idea now of what needs to be in the `core` and what doesn't. There are some java-tracker dependencies that are unnecessary for the android tracker, but we get them because we inherit from `core`.

Early list:
- [ ] SLF4J - Android logging is superior in it's own domain. SLF4J can be used in java-tracker only.
- [ ] Jackson - this can go in java-tracker since we don't need Jackson's performance gains in android
- [ ] Network implementations (http-client in android-tracker is different from java-tracker, we can do without having it in core since we don't use it there, but we still download it. Also causes warnings in Android builds.)

This would be a big change so it would be better to put this in 0.6.0 to work on once I'm done with immediate android stuff.

**Comment by alexanderdean** [comment]
This is no longer required, because: #116
